services:

    ms14:
        container_name: ms14
        hostname: ms14
        build:
            context: Microsoft
            dockerfile: Ms-14.dockerfile
#        privileged: true
        ports:
            - "25140:1433"
        volumes:
            - "../DB/Microsoft/Zoo-25/Menagerie:/scripts"
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    memory: 2G
        healthcheck:
            test: grep "Starting up database 'master'." /var/opt/mssql/log/errorlog || exit 1
            interval: 10s
            timeout: 10s
            retries: 15

    ms15:
        container_name: ms15
        hostname: ms15
        build:
            context: Microsoft
            dockerfile: Ms-15.dockerfile
        privileged: true
        ports:
            - "25150:1433"
        volumes:
            - "../DB/Microsoft/Zoo-25/Menagerie:/scripts"
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    memory: 2G
        healthcheck:
            test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" -C -t 1 || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 15

    ms16:
        container_name: ms16
        hostname: ms16
        build:
            context: Microsoft
            dockerfile: Ms-16.dockerfile
#        privileged: true
        ports:
            - "25160:1433"
        volumes:
          - "../DB/Microsoft/Zoo-25/Menagerie:/scripts"
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    memory: 2G
        healthcheck:
            test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" -C -t 1 || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 15
